apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-js-app
  name: node-js-app
  namespace: webapp
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: node-js-app
  type: NodePort